### ISSUE TITLE
Erro ao importar `moment`

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua-node#13]
Depois de instalar `moment` global.

```
var m = importar('moment')
escreva(m)
```
erros:

```
[Linha: undefined] Erro em JavaScript: undefined
Pilha de execução: undefined
```
Cenário esperado: 

- Não retornar erro no console
- Conseguir usar um ou mais métodos do `moment`

**Comment by leonelsanchesdasilva** [comment]
Fiz um teste usando o modo LAIR da versão 0.17.4.

```
Usando dialeto: padrão
Console da Linguagem Delégua v0.17 (desenvolvimento)
Pressione Ctrl + C para sair

delegua> var m = importar('moment')

delegua> escreva(m)
[Linha: 1] Erro em JavaScript: Cannot read properties of undefined (reading 'getTime')
Pilha de execução: TypeError: Cannot read properties of undefined (reading 'getTime')
    at isValid (C:\ProgramData\nvm\v16.16.0\node_modules\moment\moment.js:164:33)
    at Object.isValid$2 [as isValid] (C:\ProgramData\nvm\v16.16.0\node_modules\moment\moment.js:4270:16)
    at Object.toJSON (C:\ProgramData\nvm\v16.16.0\node_modules\moment\moment.js:4266:21)
    at JSON.stringify (<anonymous>)
    at Interpretador.paraTexto (C:\ProgramData\nvm\v16.16.0\node_modules\delegua\node_modules\@designliquido\delegua\fontes\interpretador\interpretador-base.js:937:25)
    at Interpretador.avaliarArgumentosEscreva (C:\ProgramData\nvm\v16.16.0\node_modules\delegua\node_modules\@designliquido\delegua\fontes\interpretador\interpretador-base.js:584:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Interpretador.visitarDeclaracaoEscreva (C:\ProgramData\nvm\v16.16.0\node_modules\delegua\node_modules\@designliquido\delegua\fontes\interpretador\interpretador-base.js:616:34)
    at async Escreva.aceitar (C:\ProgramData\nvm\v16.16.0\node_modules\delegua\node_modules\@designliquido\delegua\fontes\declaracoes\escreva.js:11:16)
    at async Interpretador.executar (C:\ProgramData\nvm\v16.16.0\node_modules\delegua\node_modules\@designliquido\delegua\fontes\interpretador\interpretador-base.js:947:27)
```

Aparentemente é um bug do Moment mesmo, especialmente esta parte:

```
    at isValid (C:\ProgramData\nvm\v16.16.0\node_modules\moment\moment.js:164:33)
    at Object.isValid$2 [as isValid] (C:\ProgramData\nvm\v16.16.0\node_modules\moment\moment.js:4270:16)
    at Object.toJSON (C:\ProgramData\nvm\v16.16.0\node_modules\moment\moment.js:4266:21)
    at JSON.stringify (<anonymous>)
```

Eu não sei se vale muito a pena escrever nosso próprio serializador de objeto vindo do JavaScript, mas se for relevante podemos tentar.
