### ISSUE TITLE
Erro na conversão do JavaScript para Delegua

### ISSUE THREAD

**Issue by Khovito** [DesignLiquido/delegua-node#20]
Estou tentando converter um arquivo ".js" para "delegua", porém ocorre um erro na saída do comando. Segue o comando e o erro:

`delegua --traduzir javascript-para-delegua tradut.js`

```javascript

/usr/lib/node_modules/delegua/node_modules/@designliquido/delegua-node/fontes/importador/importador-javascript.js:47
        const retornoLexador = this.lexador.mapear(conteudoDoArquivo, hashArquivo);
                                            ^

TypeError: Cannot read properties of undefined (reading 'mapear')
    at ImportadorJavaScript.importar (/usr/lib/node_modules/delegua/node_modules/@designliquido/delegua-node/fontes/importador/importador-javascript.js:47:45)
    at NucleoTraducao.traduzirArquivo (/usr/lib/node_modules/delegua/node_modules/@designliquido/delegua-node/fontes/nucleo-traducao.js:101:51)
    at Delegua.traduzirArquivo (/usr/lib/node_modules/delegua/node_modules/@designliquido/delegua-node/fontes/delegua.js:37:24)
    at principal (/usr/lib/node_modules/delegua/node_modules/@designliquido/delegua-node/execucao.js:30:25)
    at Object.<anonymous> (/usr/lib/node_modules/delegua/node_modules/@designliquido/delegua-node/execucao.js:41:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)

Node.js v19.9.0

**Comment by samuelrvg** [comment]
@Khovito Qual o conteúdo do arquivo que tentou traduzir?

**Comment by Khovito** [comment]
@samuelrvg na verdade um código simples, só para teste mesmo:

```javascript
let i = 0; 
do {
    console.log(i)
    i = i + 1
}
while (i < 5)

**Comment by leonelsanchesdasilva** [comment]
@samuelrvg @Khovito Publiquei agora há pouco a versão 0.24.5 do pacote `delegua` no NPM que deve resolver este erro. Peço para que testem e, se o problema continuar, vou trabalhar numa correção.

**Comment by Khovito** [comment]
@leonelsanchesdasilva o problema prevalece.
